---
abstract: 'Simple sub-process management for asynchronous tasks'
author:
  - 'Chris Prather C<< <perigrin@cpan.org> >>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Workers
no_index:
  directory:
    - ex
    - inc
    - t
requires:
  Moose: 0.75
  MooseX::AttributeHelpers: 0.14
  POE: 1.004
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
