---
abstract: 'Simple sub-process management for asynchronous tasks'
author:
  - 'Chris Prather <perigrin@cpan.org>'
build_requires:
  DateTime: 0
  File::Find: 0
  File::Temp: 0
  POE::Filter::Line: 0
  POE::Filter::Reference: 0
  Scalar::Util: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Workers
no_index:
  directory:
    - doc
requires:
  Moose: 0
  Moose::Role: 0
  POE: 0
  POE::Wheel::Run: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=MooseX-Workers
  homepage: http://metacpan.org/release/MooseX-Workers
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jhannah/moosex-workers.git
version: 0.20
x_authority: cpan:PERIGRIN
